//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booked_properties
    {
        public int si_no { get; set; }
        public int property_id { get; set; }
        public string property_name { get; set; }
        public string property_type { get; set; }
        public string property_address { get; set; }
        public string property_state { get; set; }
        public string property_city { get; set; }
        public string property_pin { get; set; }
        public int bhk { get; set; }
        public int seller_id { get; set; }
        public string seller_name { get; set; }
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public System.DateTime book_date { get; set; }
    }
}
