//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHouseRentManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseRentManagementEntities : DbContext
    {
        public HouseRentManagementEntities()
            : base("name=HouseRentManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking_details> booking_details { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<property> properties { get; set; }
        public virtual DbSet<property_images> property_images { get; set; }
        public virtual DbSet<seller> sellers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<booked_properties> booked_properties { get; set; }
        public virtual DbSet<customers_status> customers_status { get; set; }
        public virtual DbSet<sellers_status> sellers_status { get; set; }
    }
}
