//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.booking_details = new HashSet<booking_details>();
            this.property_images = new HashSet<property_images>();
        }
    
        public int property_id { get; set; }
        public string property_type { get; set; }
        public string property_name { get; set; }
        public string property_address { get; set; }
        public string property_state { get; set; }
        public string property_city { get; set; }
        public string property_pin { get; set; }
        public int bhk { get; set; }
        public string floor { get; set; }
        public string total_floor { get; set; }
        public int bathroom { get; set; }
        public int bedroom { get; set; }
        public int property_age { get; set; }
        public string facing { get; set; }
        public string property_size { get; set; }
        public string lease { get; set; }
        public decimal expected_rent { get; set; }
        public decimal expected_deposit { get; set; }
        public string preferred_tenants { get; set; }
        public string furnishing { get; set; }
        public string parking { get; set; }
        public string description { get; set; }
        public string property_status { get; set; }
        public System.DateTime post_date { get; set; }
        public int seller_id { get; set; }
        public string balcony { get; set; }
        public string water_supply { get; set; }
        public string gated_security { get; set; }
        public System.DateTime available_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_details> booking_details { get; set; }
        public virtual seller seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property_images> property_images { get; set; }
    }
}
