//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property_images
    {
        public int si_no { get; set; }
        public byte[] property_images1 { get; set; }
        public int property_id { get; set; }
    
        public virtual property property { get; set; }
    }
}
